Use the following code for the questions below:


a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])



In [1]:
import numpy as np


In [15]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


1. How many negative numbers are there?

In [20]:
count = (a < 0)
print(count)
sum(count)

[False False False False  True  True False False False  True False  True]


4

2. How many positive numbers are there?

In [21]:
pos_num = (a >0)
print(pos_num)
sum(pos_num)

[ True  True  True  True False False False False False False  True False]


5

3. How many even positive numbers are there?

In [28]:
pos_num = (a > 0) & ( a % 2 == 0)
print(pos_num)
sum(pos_num)
print(a [pos_num])

[ True  True  True False False False False False False False False False]
[ 4 10 12]


4. If you were to add 3 to each data point, how many positive numbers would there be?

In [32]:
plus_three = a + 3
print(plus_three)
new_pos_num = plus_three > 0
print(new_pos_num)
print(sum(new_pos_num))
print(plus_three[new_pos_num])


[ 7 13 15 26  1  2  3  3  3 -3  6 -4]
[ True  True  True  True  True  True  True  True  True False  True False]
10
[ 7 13 15 26  1  2  3  3  3  6]


5. If you squared each number, what would the new mean and standard deviation be?

In [34]:
squ_arr = a **2
print(squ_arr.mean())
squ_arr.std()


74.0


144.0243035046516

6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

(done)

7. Calculate the z-score for each data point. Recall that the z-score is given by:

Z=(x−μ)/σ


In [39]:
samp_avg = a.mean()
print(samp_avg)

numerator = a - samp_avg
print(numerator)

numerator/ (a.std())

3.0
[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [40]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [43]:
sum_of_a = sum(a)
print(sum_of_a)


55


# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [46]:
min_of_a = min(a)
print(min_of_a)

1


# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [47]:
max_of_a = max(a)
print(max_of_a)

10


# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [49]:
mean_of_a = sum_of_a/len(a)
print(mean_of_a)

5.5


# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [53]:

product = 1

for item in a:
	product = product * item
product_of_a = product
print(product_of_a)

3628800


Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [55]:

squares_of_a = [number ** 2 for number in a]
print(squares_of_a)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [59]:
odds_in_a = [num for num in a if num % 2 == 1]
print(odds_in_a)


[1, 3, 5, 7, 9]


# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [60]:
evens_in_a = [num for num in a if num % 2 == 0]
print(evens_in_a)

[2, 4, 6, 8, 10]
